### PR TITLE
Brought back hidden H* for `index` page

### PR DESCRIPTION
**Pull request by danielsokolowski**

### CODE REVIEW

**Comment by wolever** [comment]
Sorry to nitpick, but can you clean up the diff on the css file so it only shows actual changes (as opposed to what look like a bunch of whitespace changes)? When that's done, I'll merge and push.

**Comment by danielsokolowski** [comment]
Sure, I'll see what I can do tomorrow - the css changes were minimal but 
I deleted some stuff that shifted everything - but here is the live 
version for a visual test: http://sh1.danols.com:6543

On 17/10/2012 01:16, David Wolever wrote:

> Sorry to nitpick, but can you clean up the diff on the css file so it 
> only shows actual changes (as opposed to what look like a bunch of 
> whitespace changes)? When that's done, I'll merge and push.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/pyconca/pyconca/pull/63#issuecomment-9516302.

## 

Daniel Sokolowski
Web Engineer
Danols Web Engineering
http://webdesign.danols.com/
Office: 613-817-6833
Fax: 613-817-5340
Toll Free: 1-855-5DANOLS
Kingston, ON K7L 1H3, Canada

Notice of Confidentiality:
The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review re-transmission dissemination or other use of or taking of any action in reliance upon this information by persons or entities other than the intended recipient is prohibited. If you received this in error please contact the sender immediately by return electronic transmission and then immediately delete this transmission including all attachments without copying distributing or disclosing same.

**Comment by danielsokolowski** [comment]
@wolever take a look at css now - also temporarily running it at http://sh1.danols.com:6543

**Comment by wolever** [comment]
Merged, fixed a copule little issues with the home page CSS, pushed to prod.

**Comment by danielsokolowski** [comment]
Awesome, Thank you!

On 18/10/2012 20:48, David Wolever wrote:

> Merged, fixed a copule little issues with the home page CSS, pushed to 
> prod.
> 
> On 2012-10-17, at 10:02 PM, Daniel Sokolowski wrote:
> 
> > @wolever take a look now.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/pyconca/pyconca/pull/63#issuecomment-9586584.

## 

Daniel Sokolowski
http://webdesign.danols.com/

**Comment by danielsokolowski** [comment]
FYI: by product of whatever was tweaked but on small screen is now less 
readable - the one on the right is from : http://sh1.danols.com:6543/

**Comment by wolever** [comment]
Oohh, thanks. Ya, I fixed it so it looks decent on larger browsers… Could you put the media query back in so it looks good on smaller browsers?

PS: I'm just getting SSL stuff setup now?

**Comment by danielsokolowski** [comment]
Absolutely - will do.

On 18/10/2012 21:06, David Wolever wrote:

> Oohh, thanks. Ya, I fixed it so it looks decent on larger browsers… 
> Could you put the media query back in so it looks good on smaller 
> browsers?
> 
> PS: I'm just getting SSL stuff setup now?
> 
> On 2012-10-18, at 9:02 PM, Daniel Sokolowski wrote:
> 
> > FYI: by product of whatever was tweaked but on small screen is now less
> > readable - the one on the right is from : http://sh1.danols.com:6543/
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/pyconca/pyconca/pull/63#issuecomment-9586846.

## 

Daniel Sokolowski
Web Engineer
Danols Web Engineering
http://webdesign.danols.com/
Office: 613-817-6833
Fax: 613-817-5340
Toll Free: 1-855-5DANOLS
Kingston, ON K7L 1H3, Canada

Notice of Confidentiality:
The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review re-transmission dissemination or other use of or taking of any action in reliance upon this information by persons or entities other than the intended recipient is prohibited. If you received this in error please contact the sender immediately by return electronic transmission and then immediately delete this transmission including all attachments without copying distributing or disclosing same.

**Comment by danielsokolowski** [comment]
Pull request: https://github.com/pyconca/pyconca/pull/64
Code live: http://sh1.danols.com:6543/

**Pull request merged**
