### PR TITLE
Switched from Chameleon to Mako

### PR DESCRIPTION
**Pull request by kayzhu**
Rewrote templates from `.pt` to `.mako` and modified corresponding views.

### CODE REVIEW

**Comment by wolever** [comment]
Looks good. Please delete the `.pt` files which aren't needed any more and I'll merge this.

**Comment by kayzhu** [comment]
Done removing `.pt` files, I will switch the Chameleon template files for `user` to Mako now.

**Comment by wolever** [comment]
Ok. In that case, I'll wait 'till you've removed all references to Chameleon before merging.

**Comment by kayzhu** [comment]
Hmm I hope it won't be a problem now that I merged `mako-refactor` branch to `master` and deleted `mako-refactor` branch (where this pull request is based on) in my fork.

**Comment by wolever** [comment]
Actually, I think it'd probably be better if @dianaclarke was to review and accept this. She would know better than I if it's good, as she wrote the original templates.

**Comment by shazow** [comment]
:sparkles: :+1: :sparkles:

**Comment by dianaclarke** [comment]
Thanks @kayzh, I like your style!

**Comment by kayzhu** [comment]
On 2012-05-11, at 11:35 PM, diana wrote:

> Thanks @kayzh, I like your style!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pyconca/pyconca/pull/22#issuecomment-5664973

No problem, thanks for the pull ;)

**Pull request merged**
